name: custom_pin_screen
description: A flutter package to add screens with custom keyboards and pins to
  your mobile application.
version: 0.3.1
homepage: https://github.com/Mastersam07/custom_pin_screen

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
